remote_theme: just-the-docs/just-the-docs
title: AI Image Generator for VS Code
description: Generate AI-powered images directly within Visual Studio Code
baseurl: "/vscode-ai-image-generator"
url: "https://Amul-Thantharate.github.io"

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/Amul-Thantharate/vscode-ai-image-generator"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable or disable the site search
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Footer content
footer_content: "Copyright &copy; 2024. Distributed by an <a href=\"https://github.com/Amul-Thantharate/vscode-ai-image-generator/blob/main/LICENSE\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
